import { PortWatchlistItem } from '../../types';

export const DEFAULT_PORT_WATCHLIST: PortWatchlistItem[] = [
  {
    id: 'port-22',
    port: 22,
    protocol: 'tcp',
    serviceName: 'SSH',
    description: 'Secure Shell remote terminal access',
    enabled: true,
    riskNote: 'Sensitive administrative interface; ensure key-based auth and no exposed brute-force risk.',
  },
  {
    id: 'port-53',
    port: 53,
    protocol: 'tcp',
    serviceName: 'DNS',
    description: 'Domain Name System name resolution',
    enabled: true,
    riskNote: 'Verify recursion controls and DNS spoofing protections on internal infrastructure.',
  },
  {
    id: 'port-80',
    port: 80,
    protocol: 'tcp',
    serviceName: 'HTTP',
    description: 'Hypertext Transfer Protocol unencrypted web server',
    enabled: true,
    riskNote: 'Unencrypted cleartext traffic; verify redirect to HTTPS or internal microservice scope.',
  },
  {
    id: 'port-443',
    port: 443,
    protocol: 'tcp',
    serviceName: 'HTTPS',
    description: 'HTTP over TLS secure encrypted web server',
    enabled: true,
    riskNote: 'Standard secure web port; inspect certificate validity and cipher suite posture.',
  },
  {
    id: 'port-445',
    port: 445,
    protocol: 'tcp',
    serviceName: 'SMB',
    description: 'Server Message Block file & print sharing',
    enabled: true,
    riskNote: 'Critical target for lateral movement and ransomware propagation if unintentionally exposed.',
  },
  {
    id: 'port-3389',
    port: 3389,
    protocol: 'tcp',
    serviceName: 'RDP',
    description: 'Microsoft Remote Desktop Protocol',
    enabled: true,
    riskNote: 'High-risk remote administration endpoint; require Network Level Authentication (NLA) & MFA.',
  },
  {
    id: 'port-8080',
    port: 8080,
    protocol: 'tcp',
    serviceName: 'HTTP-ALT',
    description: 'Alternative HTTP port (dev servers, proxies, admin consoles)',
    enabled: true,
    riskNote: 'Frequently hosts debug consoles, Jenkins, Spring Boot actuators, or unauthenticated proxies.',
  },
  {
    id: 'port-8443',
    port: 8443,
    protocol: 'tcp',
    serviceName: 'HTTPS-ALT',
    description: 'Alternative HTTPS port (management interfaces, web services)',
    enabled: false,
    riskNote: 'Common secondary secure interface; verify access control lists and authorization headers.',
  },
  {
    id: 'port-5432',
    port: 5432,
    protocol: 'tcp',
    serviceName: 'PostgreSQL',
    description: 'PostgreSQL relational database service',
    enabled: false,
    riskNote: 'Database port should never be exposed across unmanaged subnets.',
  },
  {
    id: 'port-3306',
    port: 3306,
    protocol: 'tcp',
    serviceName: 'MySQL',
    description: 'MySQL / MariaDB database service',
    enabled: false,
    riskNote: 'Direct database listener; should be strictly isolated to application tier.',
  },
];
